version: '3.8'

services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/swagger.yaml
    volumes:
      - ./docs/swagger.yaml:/swagger.yaml
