basePath: /api
definitions:
  main.Address:
    properties:
      city:
        type: string
      country:
        type: string
      state:
        type: string
      street:
        type: string
      zip_code:
        type: string
    type: object
  main.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  main.ResponseAddress:
    properties:
      addresses:
        items:
          $ref: '#/definitions/main.Address'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: Этот эндпоинт позволяет получить адрес по географическим координатам.
  title: Address API
  version: "1.0"
paths: {}
swagger: "2.0"
